# Generated by Django 3.0.6 on 2020-06-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Anonimous', max_length=100),
        ),
    ]
